import { Inter } from "next/font/google";
import "./globals.css";
import { ParkingProvider } from "./ParkingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Co Parking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
    <script src="https://cdn.checkout.com/js/framesv2.min.js"></script>
    </head>
      <body>
        <ParkingProvider>
          {children}
        </ParkingProvider>
      </body>
    </html>
  );
}
